[package]
name = "rawspeed-utils-loop_xform"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
proc-macro2 = { version = "1.0", default-features = false, features = [] }
syn = { version = "2.0", default-features = false, features = ["proc-macro", "parsing", "full", "visit-mut", "printing"] }
quote = { version = "1.0", default-features = false, features = [] }

[lib]
proc-macro = true
path = "mod.rs"
